<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1.4 Medidas de tendência central e suas relações | Estatística Econômica I</title>
  <meta name="description" content="Livro-texto de apoio à disciplina MATF14 (Estatística Econômica I), Departamento de Estatística, UFBA." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="1.4 Medidas de tendência central e suas relações | Estatística Econômica I" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Livro-texto de apoio à disciplina MATF14 (Estatística Econômica I), Departamento de Estatística, UFBA." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1.4 Medidas de tendência central e suas relações | Estatística Econômica I" />
  
  <meta name="twitter:description" content="Livro-texto de apoio à disciplina MATF14 (Estatística Econômica I), Departamento de Estatística, UFBA." />
  

<meta name="author" content="Raydonal Ospina" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tabelas-graficos.html"/>
<link rel="next" href="dispersao.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>Estatística Econômica I</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a>
<ul>
<li class="chapter" data-level="" data-path="para-quem-é-este-livro.html"><a href="para-quem-é-este-livro.html"><i class="fa fa-check"></i>Para quem é este livro</a></li>
<li class="chapter" data-level="" data-path="por-que-as-discussões-importam-tanto-quanto-as-contas.html"><a href="por-que-as-discussões-importam-tanto-quanto-as-contas.html"><i class="fa fa-check"></i>Por que as discussões importam tanto quanto as contas</a></li>
<li class="chapter" data-level="" data-path="como-o-material-está-organizado.html"><a href="como-o-material-está-organizado.html"><i class="fa fa-check"></i>Como o material está organizado</a></li>
<li class="chapter" data-level="" data-path="um-fio-condutor-três-lentes-sobre-os-mesmos-dados.html"><a href="um-fio-condutor-três-lentes-sobre-os-mesmos-dados.html"><i class="fa fa-check"></i>Um fio condutor: três lentes sobre os mesmos dados</a></li>
<li class="chapter" data-level="" data-path="convenções-tipográficas.html"><a href="convenções-tipográficas.html"><i class="fa fa-check"></i>Convenções tipográficas</a></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografia</a></li>
<li class="chapter" data-level="" data-path="agradecimentos.html"><a href="agradecimentos.html"><i class="fa fa-check"></i>Agradecimentos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="estatística-descritiva-e-exploratória-de-dados.html"><a href="estatística-descritiva-e-exploratória-de-dados.html"><i class="fa fa-check"></i><b>1</b> Estatística Descritiva e Exploratória de Dados</a>
<ul>
<li class="chapter" data-level="1.1" data-path="populacao-amostra.html"><a href="populacao-amostra.html"><i class="fa fa-check"></i><b>1.1</b> População e amostra</a></li>
<li class="chapter" data-level="1.2" data-path="tipos-variaveis.html"><a href="tipos-variaveis.html"><i class="fa fa-check"></i><b>1.2</b> Tipos de variáveis</a></li>
<li class="chapter" data-level="1.3" data-path="tabelas-graficos.html"><a href="tabelas-graficos.html"><i class="fa fa-check"></i><b>1.3</b> Apresentação tabular e principais tipos de representação gráfica</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="tabelas-graficos.html"><a href="tabelas-graficos.html#tabelas-de-frequência"><i class="fa fa-check"></i><b>1.3.1</b> Tabelas de frequência</a></li>
<li class="chapter" data-level="1.3.2" data-path="tabelas-graficos.html"><a href="tabelas-graficos.html#razão-e-taxa-de-variação"><i class="fa fa-check"></i><b>1.3.2</b> Razão e taxa de variação</a></li>
<li class="chapter" data-level="1.3.3" data-path="tabelas-graficos.html"><a href="tabelas-graficos.html#tabelas-de-dupla-entrada"><i class="fa fa-check"></i><b>1.3.3</b> Tabelas de dupla entrada</a></li>
<li class="chapter" data-level="1.3.4" data-path="tabelas-graficos.html"><a href="tabelas-graficos.html#gráficos-para-variáveis-qualitativas"><i class="fa fa-check"></i><b>1.3.4</b> Gráficos para variáveis qualitativas</a></li>
<li class="chapter" data-level="1.3.5" data-path="tabelas-graficos.html"><a href="tabelas-graficos.html#gráficos-para-variáveis-quantitativas"><i class="fa fa-check"></i><b>1.3.5</b> Gráficos para variáveis quantitativas</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tendencia-central.html"><a href="tendencia-central.html"><i class="fa fa-check"></i><b>1.4</b> Medidas de tendência central e suas relações</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="tendencia-central.html"><a href="tendencia-central.html#média-a-partir-de-uma-tabela-de-frequências"><i class="fa fa-check"></i><b>1.4.1</b> Média a partir de uma tabela de frequências</a></li>
<li class="chapter" data-level="1.4.2" data-path="tendencia-central.html"><a href="tendencia-central.html#um-exemplo-com-dados-da-própria-turma"><i class="fa fa-check"></i><b>1.4.2</b> Um exemplo com dados da própria turma</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="dispersao.html"><a href="dispersao.html"><i class="fa fa-check"></i><b>1.5</b> Medidas de dispersão: amplitude, quantis, variância e coeficiente de variação</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="dispersao.html"><a href="dispersao.html#quantis-distância-interquartílica-e-boxplot"><i class="fa fa-check"></i><b>1.5.1</b> Quantis, distância interquartílica e boxplot</a></li>
<li class="chapter" data-level="1.5.2" data-path="dispersao.html"><a href="dispersao.html#quando-at-e-iqr-não-bastam-cidades-a-e-b"><i class="fa fa-check"></i><b>1.5.2</b> Quando AT e IQR não bastam: cidades A e B</a></li>
<li class="chapter" data-level="1.5.3" data-path="dispersao.html"><a href="dispersao.html#desvio-padrão-variância-e-coeficiente-de-variação"><i class="fa fa-check"></i><b>1.5.3</b> Desvio padrão, variância e coeficiente de variação</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="correlacao.html"><a href="correlacao.html"><i class="fa fa-check"></i><b>1.6</b> Coeficiente de correlação</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="correlacao.html"><a href="correlacao.html#aplicação-o-faturamento-das-empresas-cresceu-de-1998-para-1999"><i class="fa fa-check"></i><b>1.6.1</b> Aplicação: o faturamento das empresas cresceu de 1998 para 1999?</a></li>
<li class="chapter" data-level="1.6.2" data-path="correlacao.html"><a href="correlacao.html#aplicação-número-de-empregados-versus-faturamento"><i class="fa fa-check"></i><b>1.6.2</b> Aplicação: número de empregados versus faturamento</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="assimetria-curtose.html"><a href="assimetria-curtose.html"><i class="fa fa-check"></i><b>1.7</b> Medidas de assimetria e curtose</a></li>
<li class="chapter" data-level="1.8" data-path="fechando-o-capítulo.html"><a href="fechando-o-capítulo.html"><i class="fa fa-check"></i><b>1.8</b> Fechando o capítulo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introducao-a-teoria-das-probabilidades.html"><a href="introducao-a-teoria-das-probabilidades.html"><i class="fa fa-check"></i><b>2</b> Introdução à Teoria das Probabilidades</a>
<ul>
<li class="chapter" data-level="2.1" data-path="prob-introducao.html"><a href="prob-introducao.html"><i class="fa fa-check"></i><b>2.1</b> Introdução: o que significa “probabilidade”</a></li>
<li class="chapter" data-level="2.2" data-path="espaco-amostral-eventos.html"><a href="espaco-amostral-eventos.html"><i class="fa fa-check"></i><b>2.2</b> Espaço amostral e eventos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="espaco-amostral-eventos.html"><a href="espaco-amostral-eventos.html#operações-com-eventos-revisão-de-teoria-de-conjuntos"><i class="fa fa-check"></i><b>2.2.1</b> Operações com eventos (revisão de teoria de conjuntos)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="conceitos-probabilidade.html"><a href="conceitos-probabilidade.html"><i class="fa fa-check"></i><b>2.3</b> Conceitos e propriedades de probabilidade</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="conceitos-probabilidade.html"><a href="conceitos-probabilidade.html#modelo-de-espaço-equiprovável-e-métodos-de-contagem"><i class="fa fa-check"></i><b>2.3.1</b> Modelo de espaço equiprovável e métodos de contagem</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="probabilidade-condicional.html"><a href="probabilidade-condicional.html"><i class="fa fa-check"></i><b>2.4</b> Probabilidade condicional</a></li>
<li class="chapter" data-level="2.5" data-path="teoremas-basicos.html"><a href="teoremas-basicos.html"><i class="fa fa-check"></i><b>2.5</b> Teoremas básicos de probabilidade</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="teoremas-basicos.html"><a href="teoremas-basicos.html#teorema-da-probabilidade-total"><i class="fa fa-check"></i><b>2.5.1</b> Teorema da probabilidade total</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="independencia.html"><a href="independencia.html"><i class="fa fa-check"></i><b>2.6</b> Independência estatística</a></li>
<li class="chapter" data-level="2.7" data-path="teorema-de-bayes.html"><a href="teorema-de-bayes.html"><i class="fa fa-check"></i><b>2.7</b> Teorema de Bayes</a></li>
<li class="chapter" data-level="2.8" data-path="fechando-o-capítulo-1.html"><a href="fechando-o-capítulo-1.html"><i class="fa fa-check"></i><b>2.8</b> Fechando o capítulo</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="variaveis-aleatorias-discretas.html"><a href="variaveis-aleatorias-discretas.html"><i class="fa fa-check"></i><b>3</b> Variáveis Aleatórias Discretas</a>
<ul>
<li class="chapter" data-level="3.1" data-path="va-discreta-conceito.html"><a href="va-discreta-conceito.html"><i class="fa fa-check"></i><b>3.1</b> Conceituação de variável aleatória discreta</a></li>
<li class="chapter" data-level="3.2" data-path="va-discreta-esperanca-variancia.html"><a href="va-discreta-esperanca-variancia.html"><i class="fa fa-check"></i><b>3.2</b> Esperança e variância</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="va-discreta-esperanca-variancia.html"><a href="va-discreta-esperanca-variancia.html#definição"><i class="fa fa-check"></i><b>3.2.1</b> Definição</a></li>
<li class="chapter" data-level="3.2.2" data-path="va-discreta-esperanca-variancia.html"><a href="va-discreta-esperanca-variancia.html#propriedades-da-esperança-e-da-variância"><i class="fa fa-check"></i><b>3.2.2</b> Propriedades da esperança e da variância</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="va-discreta-fda.html"><a href="va-discreta-fda.html"><i class="fa fa-check"></i><b>3.3</b> Função de distribuição acumulada</a></li>
<li class="chapter" data-level="3.4" data-path="modelos-discretos.html"><a href="modelos-discretos.html"><i class="fa fa-check"></i><b>3.4</b> Alguns modelos probabilísticos</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="modelos-discretos.html"><a href="modelos-discretos.html#distribuição-de-bernoulli"><i class="fa fa-check"></i><b>3.4.1</b> Distribuição de Bernoulli</a></li>
<li class="chapter" data-level="3.4.2" data-path="modelos-discretos.html"><a href="modelos-discretos.html#distribuição-binomial"><i class="fa fa-check"></i><b>3.4.2</b> Distribuição Binomial</a></li>
<li class="chapter" data-level="3.4.3" data-path="modelos-discretos.html"><a href="modelos-discretos.html#distribuição-de-poisson"><i class="fa fa-check"></i><b>3.4.3</b> Distribuição de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="va-discreta-simulacao.html"><a href="va-discreta-simulacao.html"><i class="fa fa-check"></i><b>3.5</b> Da fórmula à simulação</a></li>
<li class="chapter" data-level="3.6" data-path="fechando-o-capítulo-2.html"><a href="fechando-o-capítulo-2.html"><i class="fa fa-check"></i><b>3.6</b> Fechando o capítulo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="variaveis-aleatorias-continuas.html"><a href="variaveis-aleatorias-continuas.html"><i class="fa fa-check"></i><b>4</b> Variáveis Aleatórias Contínuas</a>
<ul>
<li class="chapter" data-level="4.1" data-path="va-continua-conceito.html"><a href="va-continua-conceito.html"><i class="fa fa-check"></i><b>4.1</b> Conceituação de variável aleatória contínua</a></li>
<li class="chapter" data-level="4.2" data-path="va-continua-esperanca-variancia.html"><a href="va-continua-esperanca-variancia.html"><i class="fa fa-check"></i><b>4.2</b> Esperança e variância</a></li>
<li class="chapter" data-level="4.3" data-path="va-continua-fda.html"><a href="va-continua-fda.html"><i class="fa fa-check"></i><b>4.3</b> Função de distribuição acumulada</a></li>
<li class="chapter" data-level="4.4" data-path="modelos-continuos.html"><a href="modelos-continuos.html"><i class="fa fa-check"></i><b>4.4</b> Alguns modelos probabilísticos</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="modelos-continuos.html"><a href="modelos-continuos.html#distribuição-uniforme"><i class="fa fa-check"></i><b>4.4.1</b> Distribuição Uniforme</a></li>
<li class="chapter" data-level="4.4.2" data-path="modelos-continuos.html"><a href="modelos-continuos.html#distribuição-normal"><i class="fa fa-check"></i><b>4.4.2</b> Distribuição Normal</a></li>
<li class="chapter" data-level="4.4.3" data-path="modelos-continuos.html"><a href="modelos-continuos.html#a-regra-empírica-6895997"><i class="fa fa-check"></i><b>4.4.3</b> A regra empírica (68–95–99,7)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="fechando-o-capítulo-3.html"><a href="fechando-o-capítulo-3.html"><i class="fa fa-check"></i><b>4.5</b> Fechando o capítulo</a></li>
</ul></li>
<li class="appendix"><span><b>Apêndices</b></span></li>
<li class="chapter" data-level="A" data-path="ferramentas-rpython.html"><a href="ferramentas-rpython.html"><i class="fa fa-check"></i><b>A</b> Ferramentas de Trabalho: R e Python</a>
<ul>
<li class="chapter" data-level="A.1" data-path="instalação.html"><a href="instalação.html"><i class="fa fa-check"></i><b>A.1</b> Instalação</a></li>
<li class="chapter" data-level="A.2" data-path="r-e-python-como-calculadora.html"><a href="r-e-python-como-calculadora.html"><i class="fa fa-check"></i><b>A.2</b> R e Python como calculadora</a></li>
<li class="chapter" data-level="A.3" data-path="leitura-de-dados.html"><a href="leitura-de-dados.html"><i class="fa fa-check"></i><b>A.3</b> Leitura de dados</a></li>
<li class="chapter" data-level="A.4" data-path="funções.html"><a href="funções.html"><i class="fa fa-check"></i><b>A.4</b> Funções</a></li>
<li class="chapter" data-level="A.5" data-path="loops.html"><a href="loops.html"><i class="fa fa-check"></i><b>A.5</b> Loops</a></li>
<li class="chapter" data-level="A.6" data-path="números-aleatórios.html"><a href="números-aleatórios.html"><i class="fa fa-check"></i><b>A.6</b> Números aleatórios</a></li>
<li class="chapter" data-level="A.7" data-path="gráficos-básicos.html"><a href="gráficos-básicos.html"><i class="fa fa-check"></i><b>A.7</b> Gráficos básicos</a></li>
<li class="chapter" data-level="A.8" data-path="para-continuar-estudando-de-graça.html"><a href="para-continuar-estudando-de-graça.html"><i class="fa fa-check"></i><b>A.8</b> Para continuar estudando, de graça</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="revisao-de-calculo.html"><a href="revisao-de-calculo.html"><i class="fa fa-check"></i><b>B</b> Revisão de Cálculo</a>
<ul>
<li class="chapter" data-level="B.1" data-path="por-que-integrais-aparecem-em-probabilidade.html"><a href="por-que-integrais-aparecem-em-probabilidade.html"><i class="fa fa-check"></i><b>B.1</b> Por que integrais aparecem em probabilidade</a></li>
<li class="chapter" data-level="B.2" data-path="derivadas-o-essencial.html"><a href="derivadas-o-essencial.html"><i class="fa fa-check"></i><b>B.2</b> Derivadas: o essencial</a></li>
<li class="chapter" data-level="B.3" data-path="integrais-o-essencial.html"><a href="integrais-o-essencial.html"><i class="fa fa-check"></i><b>B.3</b> Integrais: o essencial</a>
<ul>
<li class="chapter" data-level="B.3.1" data-path="integrais-o-essencial.html"><a href="integrais-o-essencial.html#soma-de-riemann-de-onde-vem-a-integral"><i class="fa fa-check"></i><b>B.3.1</b> Soma de Riemann: de onde vem a integral</a></li>
<li class="chapter" data-level="B.3.2" data-path="integrais-o-essencial.html"><a href="integrais-o-essencial.html#teorema-fundamental-do-cálculo-versão-prática"><i class="fa fa-check"></i><b>B.3.2</b> Teorema Fundamental do Cálculo (versão prática)</a></li>
<li class="chapter" data-level="B.3.3" data-path="integrais-o-essencial.html"><a href="integrais-o-essencial.html#integrais-impróprias-intervalo-infinito"><i class="fa fa-check"></i><b>B.3.3</b> Integrais impróprias (intervalo infinito)</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="exercício-de-fixação.html"><a href="exercício-de-fixação.html"><i class="fa fa-check"></i><b>B.4</b> Exercício de fixação</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="formulario.html"><a href="formulario.html"><i class="fa fa-check"></i><b>C</b> Fórmulário e tabelas de referência</a>
<ul>
<li class="chapter" data-level="C.1" data-path="capítulo-1-estatística-descritiva.html"><a href="capítulo-1-estatística-descritiva.html"><i class="fa fa-check"></i><b>C.1</b> Capítulo 1: Estatística Descritiva</a></li>
<li class="chapter" data-level="C.2" data-path="capítulo-2-probabilidade.html"><a href="capítulo-2-probabilidade.html"><i class="fa fa-check"></i><b>C.2</b> Capítulo 2: Probabilidade</a></li>
<li class="chapter" data-level="C.3" data-path="capítulo-3-variáveis-aleatórias-discretas.html"><a href="capítulo-3-variáveis-aleatórias-discretas.html"><i class="fa fa-check"></i><b>C.3</b> Capítulo 3: Variáveis Aleatórias Discretas</a></li>
<li class="chapter" data-level="C.4" data-path="capítulo-4-variáveis-aleatórias-contínuas.html"><a href="capítulo-4-variáveis-aleatórias-contínuas.html"><i class="fa fa-check"></i><b>C.4</b> Capítulo 4: Variáveis Aleatórias Contínuas</a></li>
<li class="chapter" data-level="C.5" data-path="apêndice-b-cálculo-resumo.html"><a href="apêndice-b-cálculo-resumo.html"><i class="fa fa-check"></i><b>C.5</b> Apêndice B: Cálculo (resumo)</a></li>
<li class="chapter" data-level="C.6" data-path="tabela-valores-selecionados-da-normal-padrão.html"><a href="tabela-valores-selecionados-da-normal-padrão.html"><i class="fa fa-check"></i><b>C.6</b> Tabela: valores selecionados da Normal padrão</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://raydonal.github.io/matf14/" target="_blank">MATF14 — Página do curso</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estatística Econômica I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tendencia-central" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Medidas de tendência central e suas relações<a href="tendencia-central.html#tendencia-central" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sejam <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> os <span class="math inline">\(n\)</span> valores observados de uma variável quantitativa.</p>
<p><strong>Média aritmética.</strong> É o centro de gravidade dos dados:</p>
<p><span class="math display">\[
\bar{x} = \frac{x_1 + x_2 + \cdots + x_n}{n} = \frac{1}{n}\sum_{i=1}^n x_i.
\]</span></p>
<p><strong>Mediana.</strong> É o valor que ocupa a posição central quando os dados são ordenados: metade das
observações fica abaixo, metade acima.</p>
<p><span class="math display">\[
\text{Mediana} =
\begin{cases}
x_{\left(\frac{n+1}{2}\right)}, &amp; n \text{ ímpar}\\[4pt]
\dfrac{x_{\left(\frac{n}{2}\right)} + x_{\left(\frac{n}{2}+1\right)}}{2}, &amp; n \text{ par}
\end{cases}
\]</span></p>
<p>em que <span class="math inline">\(x_{(k)}\)</span> denota o <span class="math inline">\(k\)</span>-ésimo valor da amostra <strong>ordenada</strong>.</p>
<p><strong>Moda.</strong> É o valor (ou categoria) que ocorre com maior frequência, a única medida de tendência
central que faz sentido para variáveis qualitativas nominais.</p>
<div class="caixa-r"><strong>Uso do R: achando a moda com <code>which.max()</code></strong>, o R
não tem uma função <code>moda()</code> pronta, e a função <code>mode()</code> que existe faz outra
coisa completamente diferente, retorna o <em>modo de armazenamento</em> do objeto
(<code>"numeric"</code>, <code>"character"</code> etc.), não a moda estatística. Um jeito simples e
direto de achar a moda de uma variável qualitativa é contar com <code>table()</code> e localizar o
maior valor com <code>which.max()</code>:</div>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tendencia-central.html#cb17-1" tabindex="-1"></a><span class="fu">mode</span>(empresas<span class="sc">$</span>faturamento99)      <span class="co"># &quot;numeric&quot;: modo de ARMAZENAMENTO, não a moda!</span></span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tendencia-central.html#cb19-1" tabindex="-1"></a>tab_freq_setor <span class="ot">&lt;-</span> <span class="fu">table</span>(empresas<span class="sc">$</span>setor)</span>
<span id="cb19-2"><a href="tendencia-central.html#cb19-2" tabindex="-1"></a>tab_freq_setor[<span class="fu">which.max</span>(tab_freq_setor)]   <span class="co"># categoria mais frequente e sua contagem</span></span></code></pre></div>
<pre><code>## Embalagens 
##         31</code></pre>
<p>O mesmo truque funciona para achar a <strong>classe modal</strong> de uma variável contínua já agrupada em um
histograma, usando o objeto que <code>hist()</code> devolve quando <code>plot = FALSE</code>:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tendencia-central.html#cb21-1" tabindex="-1"></a>h_fat <span class="ot">&lt;-</span> <span class="fu">hist</span>(empresas<span class="sc">$</span>faturamento99, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-2"><a href="tendencia-central.html#cb21-2" tabindex="-1"></a>h_fat<span class="sc">$</span>mids[<span class="fu">which.max</span>(h_fat<span class="sc">$</span>counts)]   <span class="co"># ponto médio da classe mais frequente</span></span></code></pre></div>
<pre><code>## [1] 350000</code></pre>
<div id="média-a-partir-de-uma-tabela-de-frequências" class="section level3 hasAnchor" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Média a partir de uma tabela de frequências<a href="tendencia-central.html#média-a-partir-de-uma-tabela-de-frequências" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Quando os dados já vêm resumidos em uma tabela de frequências (valor <span class="math inline">\(x_i\)</span> ocorrendo <span class="math inline">\(n_i\)</span> vezes),
recalcular a média a partir dos dados brutos seria redundante, a mesma fórmula da média pode ser
reescrita diretamente em termos de <span class="math inline">\(n_i\)</span> e da frequência relativa <span class="math inline">\(f_i = n_i/n\)</span>:</p>
<p><span class="math display">\[
\bar X = \frac{1}{n}\sum_{i=1}^k n_i x_i = \sum_{i=1}^k f_i x_i,
\]</span></p>
<p>em que a soma agora percorre os <span class="math inline">\(k\)</span> valores <strong>distintos</strong> da tabela (não mais os <span class="math inline">\(n\)</span> valores
brutos). É a mesma média de sempre, só que ponderada pela frequência de cada valor em vez de somar
observação por observação.</p>
<div class="caixa-aplicacao"><strong>Aplicação: número de funcionários em 80 microempresas</strong>
</div>
<p>Uma pesquisa com 80 microempresas registrou o número de funcionários <span class="math inline">\(x\)</span> de cada uma, resumido
nesta tabela de frequências:</p>
<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabela-microempresas">Table 1.6: </span>80 microempresas, por número de funcionários
</caption>
<thead>
<tr>
<th style="text-align:right;">
<span class="math inline">\(x_i\)</span> (funcionários)
</th>
<th style="text-align:right;">
<span class="math inline">\(n_i\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(f_i=n_i/n\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(n_i x_i\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.100
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
0.188
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
0.275
</td>
<td style="text-align:right;">
44
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
0.225
</td>
<td style="text-align:right;">
54
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0.150
</td>
<td style="text-align:right;">
48
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.062
</td>
<td style="text-align:right;">
25
</td>
</tr>
</tbody>
</table>
<p>Somando a última coluna, <span class="math inline">\(\sum_i n_i x_i = 0(8)+1(15)+2(22)+3(18)+4(12)+5(5) = 186\)</span>, e como
<span class="math inline">\(n=\sum_i n_i = 80\)</span>,</p>
<p><span class="math display">\[
\bar X = \frac{186}{80} = 2{,}325 \approx 2{,}33 \text{ funcionários}.
\]</span></p>
<p>Confira com R, reconstruindo o vetor bruto de 80 valores a partir da tabela (com <code>rep()</code>) e
comparando as duas formas de calcular a mesma média:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tendencia-central.html#cb23-1" tabindex="-1"></a>x_bruto <span class="ot">&lt;-</span> <span class="fu">rep</span>(microempresas<span class="sc">$</span>x, <span class="at">times =</span> microempresas<span class="sc">$</span>n_i)   <span class="co"># os 80 valores individuais</span></span>
<span id="cb23-2"><a href="tendencia-central.html#cb23-2" tabindex="-1"></a><span class="fu">length</span>(x_bruto)                            <span class="co"># confirma n = 80</span></span></code></pre></div>
<pre><code>## [1] 80</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tendencia-central.html#cb25-1" tabindex="-1"></a><span class="fu">mean</span>(x_bruto)                              <span class="co"># média &quot;clássica&quot;, 1/n * sum(x_i)</span></span></code></pre></div>
<pre><code>## [1] 2.325</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="tendencia-central.html#cb27-1" tabindex="-1"></a><span class="fu">sum</span>(microempresas<span class="sc">$</span>f_i <span class="sc">*</span> microempresas<span class="sc">$</span>x)   <span class="co"># média ponderada, sum(f_i * x_i)</span></span></code></pre></div>
<pre><code>## [1] 2.323</code></pre>
<p>A <strong>mediana</strong> também sai direto da tabela, somando frequências acumuladas até passar da metade de
<span class="math inline">\(n=80\)</span> (a 40ª e a 41ª posição, em ordem): a classe <span class="math inline">\(x=0\)</span> acumula 8 casos, <span class="math inline">\(x=1\)</span> acumula <span class="math inline">\(8+15=23\)</span>,
<span class="math inline">\(x=2\)</span> acumula <span class="math inline">\(23+22=45\)</span>. Como <span class="math inline">\(23&lt;40\le 45\)</span> e <span class="math inline">\(23&lt;41\le45\)</span>, tanto a 40ª quanto a 41ª observação
ordenada caem na classe <span class="math inline">\(x=2\)</span>, logo a mediana é <span class="math inline">\(2\)</span>. A <strong>moda</strong> é o <span class="math inline">\(x_i\)</span> de maior <span class="math inline">\(n_i\)</span>, que é
<span class="math inline">\(x=2\)</span> (com <span class="math inline">\(n_i=22\)</span>). Note que média (<span class="math inline">\(2{,}33\)</span>), mediana (<span class="math inline">\(2\)</span>) e moda (<span class="math inline">\(2\)</span>) ficam bem próximas,
consistente com uma distribuição pouco assimétrica.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tendencia-central.html#cb29-1" tabindex="-1"></a>resumo_faturamento <span class="ot">&lt;-</span> empresas <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="tendencia-central.html#cb29-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-3"><a href="tendencia-central.html#cb29-3" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(faturamento99),</span>
<span id="cb29-4"><a href="tendencia-central.html#cb29-4" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(faturamento99),</span>
<span id="cb29-5"><a href="tendencia-central.html#cb29-5" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(faturamento99),</span>
<span id="cb29-6"><a href="tendencia-central.html#cb29-6" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(faturamento99)</span>
<span id="cb29-7"><a href="tendencia-central.html#cb29-7" tabindex="-1"></a>  )</span>
<span id="cb29-8"><a href="tendencia-central.html#cb29-8" tabindex="-1"></a>resumo_faturamento <span class="sc">|&gt;</span> <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
mediana
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
334264.9
</td>
<td style="text-align:right;">
327898
</td>
<td style="text-align:right;">
74392
</td>
<td style="text-align:right;">
685430
</td>
</tr>
</tbody>
</table>
<div class="caixa-economia"><strong>Leitura econômica</strong>, a média de faturamento
(R$ 334.265 mil) fica bem acima da mediana
(R$ 327.898 mil). Isso é a assinatura de uma
distribuição assimétrica à direita: um pequeno número de empresas muito grandes "puxa" a média para
cima, enquanto a mediana, insensível a esses valores extremos, continua descrevendo a empresa
"típica". É exatamente o mesmo fenômeno da distribuição de renda de um país: a renda média nacional
é sistematicamente maior que a renda mediana, e a razão entre as duas já é, informalmente, um
primeiro indicador (bruto) de desigualdade.</div>
<p>A relação entre as três medidas é informativa sobre a <strong>forma</strong> da distribuição (retomada na Seção
<a href="assimetria-curtose.html#assimetria-curtose">1.7</a>): em distribuições aproximadamente simétricas, média <span class="math inline">\(\approx\)</span> mediana
<span class="math inline">\(\approx\)</span> moda; em distribuições assimétricas à direita (cauda longa de valores altos, como renda
ou faturamento), tipicamente moda <span class="math inline">\(&lt;\)</span> mediana <span class="math inline">\(&lt;\)</span> média; em assimetria à esquerda, a ordem se
inverte.</p>
<div class="caixa-discussao"><strong>Para discutir</strong>

<p><strong>1.</strong> O Ministério do Trabalho divulga o "salário médio" de uma categoria
profissional. Um sindicato, ao negociar reajuste, prefere divulgar a mediana. Explique a motivação
de cada escolha, e o que isso revela sobre como estatísticas descritivas podem ser selecionadas
estrategicamente, mesmo sem nenhuma delas ser "falsa".</p>

<p><strong>2.</strong> Se a variável fosse escolaridade (ordinal, com categorias "fundamental",
"médio", "superior"), faria sentido calcular uma "escolaridade média"? E uma "escolaridade
mediana"? Justifique a diferença.</p>

<p><strong>3.</strong> Pense em uma variável econômica que você esperaria ter moda muito diferente
da média (por exemplo, preço de imóveis em uma cidade com bairros muito distintos). Qual seria a
consequência prática de um agente imobiliário anunciar "o preço médio dos imóveis da cidade" sem
qualificar por bairro?</p>

<p><strong>4.</strong> Um fundo de investimento anuncia "retorno médio anualizado de 15% nos
últimos 5 anos". Que pergunta sobre a mediana e sobre a variabilidade ano a ano você faria antes de
decidir investir, só com base no que já foi discutido até aqui?</p>

<p><strong>5.</strong> É possível uma distribuição ter média, mediana e moda exatamente iguais e,
ainda assim, ser muito diferente de uma distribuição em forma de sino simétrica (pense, por
exemplo, em uma distribuição bimodal simétrica)? O que isso ensina sobre os limites de resumir uma
distribuição inteira só pelas medidas de tendência central?</p>
</div>
</div>
<div id="um-exemplo-com-dados-da-própria-turma" class="section level3 hasAnchor" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Um exemplo com dados da própria turma<a href="tendencia-central.html#um-exemplo-com-dados-da-própria-turma" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As melhores bases de dados para praticar Estatística Descritiva, às vezes, são as mais simples de
coletar, inclusive os dados da própria turma. Duas ilustrações de turmas reais de MATF14 em
semestres anteriores, lidas diretamente do histograma e resolvidas com a <strong>fórmula da média a
partir de uma tabela de frequências</strong> da seção anterior, exatamente o tipo de situação em que ela é
indispensável: não há mais acesso à nota individual de cada aluno, só à contagem por faixa.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-notas-prova1"></span>
<img src="images/notas_prova1_matf14.png" alt="Distribuição das notas da Prova 1 em uma turma real de MATF14 (2025.2)." width="75%" />
<p class="caption">
Figure 1.4: Distribuição das notas da Prova 1 em uma turma real de MATF14 (2025.2).
</p>
</div>
<p>Lendo a altura de cada barra do histograma (classes de amplitude 1, de 0 a 10), obtém-se a tabela
de frequências abaixo, com o ponto médio de cada classe como representante <span class="math inline">\(x_i\)</span>:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="tendencia-central.html#cb30-1" tabindex="-1"></a>notas_turma <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb30-2"><a href="tendencia-central.html#cb30-2" tabindex="-1"></a>  <span class="at">classe =</span> <span class="fu">c</span>(<span class="st">&quot;[0,1)&quot;</span>, <span class="st">&quot;[1,2)&quot;</span>, <span class="st">&quot;[2,3)&quot;</span>, <span class="st">&quot;[3,4)&quot;</span>, <span class="st">&quot;[4,5)&quot;</span>, <span class="st">&quot;[5,6)&quot;</span>,</span>
<span id="cb30-3"><a href="tendencia-central.html#cb30-3" tabindex="-1"></a>             <span class="st">&quot;[6,7)&quot;</span>, <span class="st">&quot;[7,8)&quot;</span>, <span class="st">&quot;[8,9)&quot;</span>, <span class="st">&quot;[9,10)&quot;</span>),</span>
<span id="cb30-4"><a href="tendencia-central.html#cb30-4" tabindex="-1"></a>  <span class="at">x_i  =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">9.5</span>, <span class="at">by =</span> <span class="dv">1</span>),</span>
<span id="cb30-5"><a href="tendencia-central.html#cb30-5" tabindex="-1"></a>  <span class="at">n_i  =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">7</span>)</span>
<span id="cb30-6"><a href="tendencia-central.html#cb30-6" tabindex="-1"></a>)</span>
<span id="cb30-7"><a href="tendencia-central.html#cb30-7" tabindex="-1"></a>n_turma <span class="ot">&lt;-</span> <span class="fu">sum</span>(notas_turma<span class="sc">$</span>n_i)</span>
<span id="cb30-8"><a href="tendencia-central.html#cb30-8" tabindex="-1"></a>media_turma   <span class="ot">&lt;-</span> <span class="fu">sum</span>(notas_turma<span class="sc">$</span>n_i <span class="sc">*</span> notas_turma<span class="sc">$</span>x_i) <span class="sc">/</span> n_turma</span>
<span id="cb30-9"><a href="tendencia-central.html#cb30-9" tabindex="-1"></a>n_turma; <span class="fu">round</span>(media_turma, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<pre><code>## [1] 6.72</code></pre>
<p>Com <span class="math inline">\(n=\)</span> 32 alunos, a média é <span class="math inline">\(\bar X = \sum n_i x_i / n \approx\)</span>
6.72. Para a mediana, acumulam-se as frequências até passar de <span class="math inline">\(n/2=16\)</span>: a 16ª
e a 17ª observação (ordenadas) caem ambas na classe <span class="math inline">\([7,8)\)</span> (frequência acumulada sobe de 15 para
20 nessa classe), logo a mediana <span class="math inline">\(\approx 7{,}5\)</span>. A moda é a classe de maior frequência, <span class="math inline">\([9,10)\)</span>
(7 alunos), representada por <span class="math inline">\(9{,}5\)</span>. Como <strong>média (<span class="math inline">\(\approx 6{,}7\)</span>) <span class="math inline">\(&lt;\)</span> mediana (<span class="math inline">\(7{,}5\)</span>) <span class="math inline">\(&lt;\)</span> moda
(<span class="math inline">\(9{,}5\)</span>)</strong>, a distribuição é <strong>assimétrica à esquerda</strong>: uma cauda de notas baixas (a barra
zerada em <span class="math inline">\([6,7)\)</span>, um “vale” entre dois grupos de alunos) puxa a média para baixo, mesmo com a
maior concentração de alunos nas notas mais altas, o oposto do padrão visto no faturamento das
empresas (cauda à <em>direita</em>). É a assinatura típica de uma prova em que a maioria da turma foi bem,
mas um grupo minoritário teve desempenho bem abaixo do restante.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-letras-nomes"></span>
<img src="images/letras_nomes_matf14.png" alt="Número de letras no nome completo dos alunos de uma turma real de MATF14 (2025.2)." width="75%" />
<p class="caption">
Figure 1.5: Número de letras no nome completo dos alunos de uma turma real de MATF14 (2025.2).
</p>
</div>
<p>O mesmo procedimento aplicado ao histograma do número de letras no nome completo (classes de
amplitude 4, exceto a última):</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="tendencia-central.html#cb33-1" tabindex="-1"></a>letras_turma <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb33-2"><a href="tendencia-central.html#cb33-2" tabindex="-1"></a>  <span class="at">x_i  =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">20</span>, <span class="dv">24</span>, <span class="dv">28</span>, <span class="dv">32</span>, <span class="dv">36</span>, <span class="dv">39</span>),</span>
<span id="cb33-3"><a href="tendencia-central.html#cb33-3" tabindex="-1"></a>  <span class="at">n_i  =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">15</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb33-4"><a href="tendencia-central.html#cb33-4" tabindex="-1"></a>)</span>
<span id="cb33-5"><a href="tendencia-central.html#cb33-5" tabindex="-1"></a>n_letras   <span class="ot">&lt;-</span> <span class="fu">sum</span>(letras_turma<span class="sc">$</span>n_i)</span>
<span id="cb33-6"><a href="tendencia-central.html#cb33-6" tabindex="-1"></a>media_letras   <span class="ot">&lt;-</span> <span class="fu">sum</span>(letras_turma<span class="sc">$</span>n_i <span class="sc">*</span> letras_turma<span class="sc">$</span>x_i) <span class="sc">/</span> n_letras</span>
<span id="cb33-7"><a href="tendencia-central.html#cb33-7" tabindex="-1"></a>n_letras; <span class="fu">round</span>(media_letras, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 37</code></pre>
<pre><code>## [1] 26.68</code></pre>
<p>Com <span class="math inline">\(n=\)</span> 37 alunos, <span class="math inline">\(\bar X \approx\)</span> 26.68 letras. A mediana está na
19ª posição (de 37), que cai na classe <span class="math inline">\([26,30)\)</span> (frequência acumulada sobe de 15 para 30
nessa classe), a mesma classe da moda (15 alunos, a maior frequência). Aqui média (<span class="math inline">\(\approx26{,}7\)</span>),
mediana e moda (<span class="math inline">\(28\)</span>) ficam próximas, uma distribuição quase simétrica, um exercício quase lúdico
(contar letras em nomes) que ainda assim segue exatamente o mesmo ferramental estatístico de uma
variável econômica séria.</p>
<div class="caixa-discussao"><strong>Para discutir</strong>

<p><strong>1.</strong> A distribuição das notas é assimétrica à esquerda, a das letras nos nomes é
aproximadamente simétrica. Se você fosse o professor da disciplina e só pudesse olhar essas duas
estatísticas (média e mediana) da prova, o que a diferença entre elas (mediana \(2{,}5\) pontos acima
da média) sugere sobre calibrar a prova para a próxima aplicação?</p>

<p><strong>2.</strong> Seria possível repetir o exercício do número de letras nos nomes com a sua
própria turma nesta disciplina? Qual forma você esperaria ver, simétrica, assimétrica à direita, ou
outra, e por quê?</p>

<p><strong>3.</strong> Ao ler os valores de um histograma já pronto (em vez dos dados brutos),
usa-se o ponto médio de cada classe como \(x_i\). Que tipo de erro (para mais ou para menos) essa
aproximação pode introduzir na média calculada, comparada com a média exata que só seria possível
com a nota individual de cada aluno?</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tabelas-graficos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="dispersao.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
